site_name: 'Quix Docs'
site_description: 'Quix SDK Documentation'
repo_url: https://github.com/quixai/quix-streams/docs
edit_uri: edit/master/docs

nav:
    - 'Introduction': 'sdk/introduction.md'
    - 'Kafka and Quix SDK': 'sdk/kafka.md'
    - 'Features overview':
      - 'Streaming context': 'sdk/features/streaming-context.md'
      - 'In-memory processing': 'sdk/features/in-memory-processing.md'
      - 'Built-in buffers': 'sdk/features/builtin-buffers.md'
      - 'Support for Data Frames': 'sdk/features/data-frames.md'
      - 'Message splitting': 'sdk/features/message-splitting.md'
      - 'Message compression': 'sdk/features/message-compression.md'
      - 'Data serialization': 'sdk/features/data-serialization.md'
      - 'Multiple data types': 'sdk/features/multiple-data-types.md'
      - 'Broker configuration': 'sdk/features/broker-configuration.md'
      - 'Checkpointing': 'sdk/features/checkpointing.md'
      - 'Horizontal scaling': 'sdk/features/horizontal-scaling.md'
      - 'Integrations': 'sdk/features/integrations.md'
      - 'Portability': 'sdk/features/portability.md'
    - 'Connect to Quix': 'sdk/connect.md'
    - 'Writing data': 'sdk/write.md'
    - 'Reading data': 'sdk/read.md'
    - 'Processing data': 'sdk/process.md'
    - 'State management': 'sdk/state-management.md'
    - 'Local environment':
      - 'Set up local environment': 'sdk/python-setup.md'
      - 'Set up docker environment': 'sdk/docker-setup.md'
